#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod counter;
pub mod events_lib;
pub mod i_events;
pub mod i_irm;
pub mod i_morpho;
pub mod i_morpho_base;
pub mod i_morpho_flash_loan_callback;
pub mod i_morpho_liquidate_callback;
pub mod i_morpho_repay_callback;
pub mod i_morpho_static_typing;
pub mod i_morpho_supply_callback;
pub mod i_morpho_supply_collateral_callback;
pub mod i_oracle;
pub mod ierc20;
pub mod ierc20_permit;
pub mod liquidator;
pub mod market_params_lib;
pub mod safe_erc20;
pub mod shared_types;
